### ISSUE TITLE
Change to request animation

### ISSUE THREAD

**Issue by Deamoner** [yoyota/react-posenet#18]
I pulled your work and it works pretty flawlessly. I just noticed performance compared to other solutions is a bit slow. I notice you set your own frame window timing mechanism, others seem to just be using the request animation function. Moving to that should make it as fast. Thoughts?

**Comment by yoyota** [comment]
Thanks for your opinion, In short I will change to request animation as default option

The reason why i use setInterval instead of requestAnimationFrame was setInetrval can adjust pose estimation frequency
Fast frequency consumes more power. when i run react-posenet on mobile devices battery decreases so fast. I thought slow down inference rate can help battery time.  

In current version you can adjust frequency using frameRate parameter. 

>frameRate parameter affects how often estimation occurs. react-posenet internally do
>setInterval(() => { estimatePose() } , (1000 / frameRate)) to estimate image continuously

**Comment by Deamoner** [comment]
Yes I can see why you did your approach. I had it default so I assume that is the default config. Perhaps we can come up with a hybrid approach for skipping frames. 

Also I was thinking of adding in the drawskeletal as an option, I just copied it over from the posenet repo

**Comment by yoyota** [comment]
@Deamoner  yes [tfjs posenet repo](https://github.com/tensorflow/tfjs-models/tree/master/posenet) already implemented showing skeleton.  
 but I didn't add it yet here. contributions are always welcome thanks.
